#!/system/bin/sh
PATH_SDCARD=/sdcard
PATH_MNT_SDCARD=/mnt/sdcard
PATH_STORAGE_SDCARD0=/storage/sdcard0
PATH_SOURCE_STORAGE=/storage/emulated/0

if [ 1 -eq $(getprop persist.sys.primarysd) ];then
    PATH_SOURCE_STORAGE=/mnt/ext_sdcard
fi

mount -o remount /

if [ -d ${PATH_SDCARD} ];then 
    rm ${PATH_SDCARD}
fi 
ln -s ${PATH_SOURCE_STORAGE} ${PATH_SDCARD}

if [ -d ${PATH_MNT_SDCARD} ];then 
    rm ${PATH_MNT_SDCARD}
fi 
ln -s ${PATH_SOURCE_STORAGE} ${PATH_MNT_SDCARD}

if [ -d ${PATH_STORAGE_SDCARD0} ];then 
    rm ${PATH_STORAGE_SDCARD0}
fi 
ln -s ${PATH_SOURCE_STORAGE} ${PATH_STORAGE_SDCARD0}

mount -o remount -r /
